
POST http://localhost:3000/api/auth/signup HTTP/1.1
content-type: application/json
{
    "email":"test12@email.com",
    "username":"test12",
    "password":"password12",
    "address" : {
        "street":"2564 Westton Rd",
        "city": "Toronto",
        "province": "Ontario",
        "zip_code": "M9N 1G4"
    }
}